# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

strategy:
  matrix:
    node_8_x:
      node_version: 8.x
    node_9_x:
      node_version: 9.x

variables:
  buildConfiguration: 'Release'

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/Battleship

- task: rsjx
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: src/Battleship

#Restore
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: Restore
  
#Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build' 
    projects: '**/*.csproj'
  displayName: 'Build $(buildConfiguration)'

#Test
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: Tests